"""Initial version

Revision ID: 2ef22e5bc2b0
Revises: 
Create Date: 2019-09-03 16:46:55.658573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ef22e5bc2b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
                    sa.Column('issued_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('remote_addr', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('trips',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('trips_version',
                    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
                    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
                    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
                    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'transaction_id')
                    )
    op.create_index(op.f('ix_trips_version_end_transaction_id'), 'trips_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_trips_version_operation_type'), 'trips_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_trips_version_transaction_id'), 'trips_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_version_transaction_id'), table_name='trips_version')
    op.drop_index(op.f('ix_trips_version_operation_type'), table_name='trips_version')
    op.drop_index(op.f('ix_trips_version_end_transaction_id'), table_name='trips_version')
    op.drop_table('trips_version')
    op.drop_table('trips')
    op.drop_table('transaction')
    # ### end Alembic commands ###
